base_model: /content/pretrained_models/Spark-TTS-0.5B/LLM
load_in_4bit: false
load_in_8bit: false

trust_remote_code: true
strict: false

datasets:
  - path: /content/SparkTTS-Finetune/sample_output/sample_data.jsonl
    type: completion

dataset_prepared_path:
val_set_size: 0.05
output_dir: ./outputs/out

sequence_len: 1024
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 50
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 50
xformers_attention:
flash_attention: false

warmup_steps: 10
evals_per_epoch: 1
save_steps: 500
debug:
deepspeed:
weight_decay: 0.0
